FROM golang:1.15-buster as gobuild

COPY .    /go/src/github.com/koestler/dnsdock/
WORKDIR   /go/src/github.com/koestler/dnsdock/

RUN go get -v
RUN ./build.sh
RUN mv dnsdock /go/bin/dnsdock

FROM scratch
EXPOSE 80/tcp
EXPOSE 53/tcp
EXPOSE 53/udp
COPY --from=gobuild /go/bin/dnsdock /dnsdock
ENTRYPOINT ["/dnsdock"]
